version: '3.3'
services:
#================================
#      POSTGRES
#================================
  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

    expose:
      - "5432"
#================================
#       Redis
#================================
  redis:
    image: redis:alpine
    hostname: redis
    container_name: t_bot_redis
    env_file:
      - .env
    volumes:
      - redis_volume:/data
#================================
#       Redislabs
#================================
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: t_bot_redislabs
    ports:
      - '8001:8001'
    volumes:
      - redis_insight_volume:/db
    depends_on:
      - redis
#================================
#       App
#================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file:
      - .env
    volumes:
      - ./src:/src
    depends_on:
      - db
      - redis

#================================
#         NETWORK
#================================
networks:
  auth-network:
    external:
      name: src-network

#================================
#         VOLUMES
#================================
volumes:
  postgres_data:
  redis_volume:
  redis_insight_volume:
